name = "qfax-website"
compatibility_date = "2025-10-28"

# Static site deployed via: wrangler pages deploy . --project-name=qfax-website
# No additional config needed - directory specified in deploy command
